export const demoFiles: Readonly<Record<string, string>> = {
  'src/app.tsx': [
    "import './styles.css'",
    '',
    'const projects = [',
    "  { name: '客户工作台', owner: '林悦', status: '进行中' },",
    "  { name: '订单管理', owner: '陈晨', status: '待评审' },",
    "  { name: '数据看板', owner: '周宁', status: '已完成' },",
    ']',
    '',
    'export const App = () => (',
    '  <main className="workspace">',
    '    <header>',
    '      <p>团队空间</p>',
    '      <h1>项目概览</h1>',
    '    </header>',
    '    <table>',
    '      <thead>',
    '        <tr><th>项目</th><th>负责人</th><th>状态</th></tr>',
    '      </thead>',
    '      <tbody>',
    '        {projects.map(project => (',
    '          <tr key={project.name}>',
    '            <td>{project.name}</td>',
    '            <td>{project.owner}</td>',
    '            <td>{project.status}</td>',
    '          </tr>',
    '        ))}',
    '      </tbody>',
    '    </table>',
    '  </main>',
    ')',
    '',
  ].join('\n'),
  'src/styles.css': [
    '.workspace {',
    '  padding: 32px;',
    '  color: #192332;',
    '  font-family: system-ui, sans-serif;',
    '}',
    '',
    'table {',
    '  width: 100%;',
    '  border-collapse: collapse;',
    '}',
    '',
    'th, td {',
    '  padding: 16px;',
    '  border-bottom: 1px solid #d8e0eb;',
    '  text-align: left;',
    '}',
    '',
  ].join('\n'),
  'README.md': [
    '# 示例项目',
    '',
    '一个简单的 React 团队管理工作台，包含项目名称、负责人和状态。',
    '',
    '这些文件仅用于演示源码浏览，尚未连接编译器，不能运行或编辑。',
    '它们不是完整的 Vite 项目，也不定义 Gamma Compose 的项目协议。',
    '',
  ].join('\n'),
}
